services:
  postgres:
    container_name: database
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretPass!234
      PGDATA: /data/postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../../sql/database.sql:/docker-entrypoint-initdb.d/database.sql
    ports:
      - '5432:5432'
    restart: unless-stopped
  redis:
    container_name: cache
    image: redis:7.2-alpine
    command: [sh, -c, 'rm -f /data/dump.rdb && redis-server --save 20 1 --loglevel warning']
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - cache:/data
  frontend:
    container_name: frontend
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    image: frontend
    ports:
      - "3001:3000"
      - "5556:5555"
    environment:
      - NODE_ENV=development
    volumes:
      - ../../.:/app
volumes:
  postgres-data:
    driver: local
  cache:
    driver: local